name: doc create images
on:
    push:
        branches: master

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:

  #start update to server actions
  build-image-at-ghcr:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: log in container registry
        uses: docker/login-action@v1
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: extract metadata (tags, labels) for docker
        id: meta
        uses: docker/metadata-action@v3
        with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}


      - name: build and push docker image
        uses: docker/build-push-action@v2
        with:
            context: .
            file: Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outpus.labels }}
